std = "roblox"

exclude = ["test/*"]

[lints]
global_usage = "allow"
unused_variable = "allow"
shadowing = "allow"
parenthese_conditions = "allow"
multiple_statements = "allow"
# script.Parent = parent is not allowed if this isn't set to allow??
incorrect_standard_library_use = "allow"
